# Generated by Django 5.0.6 on 2024-06-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_avatarimage_contactinfo_telegram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_me',
        ),
        migrations.DeleteModel(
            name='AvatarImage',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='Men',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
